### ISSUE TITLE
attach_file and _slurp does not use binmode for files

### ISSUE THREAD

**Issue by GwenDragon** [rjbs/Email-Stuffer#14]
attach_file() and _slurp does not use binmode for reading file data.    
As a result attachments get sometimes corrupted.

if IO::All::File is installed Email::Stuffer uses method io()->all from IO::All.
But all() does not set binmode as default!

Code at https://metacpan.org/source/RJBS/Email-Stuffer-0.009/lib/Email/Stuffer.pm#L222

    $body = $body_arg->all;

should be

     $body = $body_arg->binmode()->all;

   
   
and https://metacpan.org/source/RJBS/Email-Stuffer-0.009/lib/Email/Stuffer.pm#L246

    open( SLURP, "<$file" ) or return undef;

should be

    open( SLURP, "<$file" ) or return undef;
    binmode SLURP;

   

Tested on Windows 7 with attachment files of ODS (Libreoffice Table) and XLSX (Excel) format.

More information: <http://labs.gwendragon.de/bugs/Perl/Email-Stuffer/Bug-Email-Stuffer-attachments.html>

* Testcase: <http://labs.gwendragon.de/bugs/Perl/Email-Stuffer/Stuffer-testcase.tar.gz>
* Diff: <http://labs.gwendragon.de/bugs/Perl/Email-Stuffer/Stuffer.pm.diff>
* Patched Stuffer.pm <http://labs.gwendragon.de/bugs/Perl/Email-Stuffer/Stuffer_fixed.pm>

Please check this.

**Comment by rjbs** [comment]
The IO::All patch from frioux is now applied.  The other code has been fixed in the meantime!
