### ISSUE TITLE
Corrupted emails when body_text is empty

### ISSUE THREAD

**Issue by wbiker** [rjbs/Email-Stuffer#16]
First thanks for the module.

Unfortunately, I have a problem with it if sending emails with attachment, but without body text.

I send some files to me and sometimes the mail was corrupted. The attachment was shown, but was only 1 kb in size. I recognized that this only happens if I send a email without body text.

The email is created with:
```
my $transport = Email::Sender::Transport::SMTPS->new(
   host => 'ip',
   ssl => 'starttls',
   ssl_username => 'user',
   ssl_password => 'pwd',
   SSL_verify_mode => SSL_VERIFY__NONE,
);

my $mail = Email::Stuffer->new;
$mail->to('email1,email2,email3');
$mail->from('myemail');
$email->subject('Subject');

$email->attach_file('file in the same directory');

my $body;
$body = $message if $message;
$mail->text_body($body);
$mail->transport($transport);
$mail->send_or_die();
```

Thanks

**Comment by krismatthews** [comment]
@wbiker Are you still able to reproduce this? My own test program (with a 186kb png) succeeds and the attachment is intact. Admittedly the email with `text_body(undef)` looks a bit odd - 

```
Date: Sun, 9 Oct 2016 13:05:56 -0600
MIME-Version: 1.0
From: kris@mtthws.net
To: redacted
Subject: this is only a subject
Content-Transfer-Encoding: base64
Content-Type: image/jpeg
Message-Id: <redacted>

<base64 encoded data follows>
```

but I cannot find any resource saying this isn't valid. It anecdotally works with the systems I've tried to reproduce it on (Gmail and Fastmail) - what system are you using where it fails? 

If this is still happening for you, what versions of Email::Stuffer, Email::MIME and Email::Sender are you using? (`cpan -D module::name`)

**Comment by wbiker** [comment]
Hmm, I just initialized $body with a string and completely forget about this. 
Will try it again with empty body.

**Comment by wbiker** [comment]
OK, I clode this issue. I sent an email with empty body without any issues.
