### ISSUE TITLE
Honour Bcc header

### ISSUE THREAD

**Issue by stevenl** [rjbs/Email-Stuffer#17]
I get that for Email::Sender::Simple, not honouring Bcc is not a bug. But would you consider putting it in Email::Stuffer since this module is intended for "slap it together and fire it off" situations?

**Comment by slobo** [comment]
Yes, it would be great if Stuffer could automatically hand off  `bcc` to the transport. Currently, we have to do this:

```perl
Email::Stuffer->from     ('cpan@ali.as'             )
              ->to       ('santa@northpole.org'     )
              ->bcc      ('bunbun@sluggy.com'       )
              ->text_body('hi!'                      )

              ->send({ to => ['santa@northpole.org', 'bunbun@sluggy.com'] });

```

In which case one could omit `bcc` header altogether as SMTP server should strip it anyways, no? 
Or are there some transports / SMTP servers that will  auto extract recipients from BCC field automatically so we could break peoples existing code?
