### ISSUE TITLE
Returning undef from methods designed for chaining causes headaches

### ISSUE THREAD

**Issue by timbunce** [rjbs/Email-Stuffer#20]
The docs promote the use of chaining:
```
  Email::Stuffer->to('Simon Cozens<simon@somewhere.jp>')
                ->from('Santa@northpole.org')
                ->text_body("You've been good this year. No coal for you.")
                ->attach_file('choochoo.gif')
                ->send;
```
but there's no mention of the fact that some methods, like `subject` and `to` will return undef in some cases. In those cases the error behaviour is Less Than Awesome.

This has come up before in #8 in relation to `subject()`. We just hit this again in related to `to()`.

Given that the docs say:
>  this is very much a module for those "slap it together and fire it off" situations, but that still has enough grunt behind the scenes to do things properly.

and
> this module is still subject to name and/or API changes

I'd like to propose that exceptions be thrown in these cases.

**Comment by rjbs** [comment]
I've done this in 6881b7a
