### ISSUE TITLE
Test Failure with older versions of Email* modules.

### ISSUE THREAD

**Issue by colinnewell** [rjbs/Email-Stuffer#28]
With these modules I got test failures,

```
#     Email::MIME                         any    1.911
#     Email::MIME::Creator                any    1.911
#     Email::Sender::Simple               any 0.120002
#     Email::Sender::Transport::Test 0.120000 0.120002

#   Failed test 'Email contains from name'
#   at t/alternative.t line 26.
#                   'Date: Thu, 28 Apr 2016 16:12:56 +0100
# MIME-Version: 1.0
# From: =?UTF-8?Q?Adam_Kennedy=3Cadam=40phase-n=2Ecom=3E?=
# To: =?UTF-8?Q?adam=40phase-n=2Ecom?=
# Subject: =?UTF-8?Q?Hello_To=3A!?=
# Content-Type: multipart/alternative; boundary="1461856376.6E401440.14731"
# 
# 

```

For the full report see the gist - https://gist.github.com/colinnewell/81728b5f494b2340f5f72b576fac6e99

After an upgrade I didn't.  It's probably simplest to just upgrade your dependency versions.

/opt/perl5/bin/cpanm Email::MIME Email::MIME::Creator Email::Sender::Simple Email::Sender::Transport::Test
--> Working on Email::MIME
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Email-MIME-1.937.tar.gz ... OK
Configuring Email-MIME-1.937 ... OK
==> Found dependencies: Email::Simple, Email::MIME::Encodings, Email::MIME::ContentType
--> Working on Email::Simple
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Email-Simple-2.210.tar.gz ... OK
Configuring Email-Simple-2.210 ... OK
Building and testing Email-Simple-2.210 ... OK
Successfully installed Email-Simple-2.210 (upgraded from 2.102)
--> Working on Email::MIME::Encodings
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Email-MIME-Encodings-1.315.tar.gz ... OK
Configuring Email-MIME-Encodings-1.315 ... OK
Building and testing Email-MIME-Encodings-1.315 ... OK
Successfully installed Email-MIME-Encodings-1.315 (upgraded from 1.313)
--> Working on Email::MIME::ContentType
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Email-MIME-ContentType-1.018.tar.gz ... OK
Configuring Email-MIME-ContentType-1.018 ... OK
Building and testing Email-MIME-ContentType-1.018 ... OK
Successfully installed Email-MIME-ContentType-1.018 (upgraded from 1.015)
Building and testing Email-MIME-1.937 ... OK
Successfully installed Email-MIME-1.937 (upgraded from 1.911)
--> Working on Email::Sender::Simple
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Email-Sender-1.300028.tar.gz ... OK
Configuring Email-Sender-1.300028 ... OK
==> Found dependencies: Email::Abstract, Net::SMTP
--> Working on Email::Abstract
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Email-Abstract-3.008.tar.gz ... OK
Configuring Email-Abstract-3.008 ... OK
Building and testing Email-Abstract-3.008 ... OK
Successfully installed Email-Abstract-3.008 (upgraded from 3.004)
--> Working on Net::SMTP
Fetching http://www.cpan.org/authors/id/S/SH/SHAY/libnet-3.08.tar.gz ... OK
==> Found dependencies: ExtUtils::MakeMaker
--> Working on ExtUtils::MakeMaker
Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.14.tar.gz ... OK
Configuring ExtUtils-MakeMaker-7.14 ... OK
Building and testing ExtUtils-MakeMaker-7.14 ... OK
Successfully installed ExtUtils-MakeMaker-7.14 (upgraded from 6.62)
Configuring libnet-3.08 ... OK
==> Found dependencies: Socket
--> Working on Socket
Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/Socket-2.021.tar.gz ... OK
Configuring Socket-2.021 ... OK
Building and testing Socket-2.021 ... OK
Successfully installed Socket-2.021 (upgraded from 1.94)
Building and testing libnet-3.08 ... OK
Successfully installed libnet-3.08 (upgraded from 2.31)
Building and testing Email-Sender-1.300028 ... OK
Successfully installed Email-Sender-1.300028 (upgraded from 0.120002)
9 distributions installed

**Comment by rjbs** [comment]
Thanks, 1.920 seems to work.  Updated!
