### ISSUE TITLE
Why is the transport module not automatically loaded? Load it automatically

### ISSUE THREAD

**Issue by akarelas** [rjbs/Email-Stuffer#29]
In the documentation it says:

"In neither case will a module be automatically loaded."

I think our code would be prettier and tidier if the transport module were automatically loaded. So why isn't it?

**Comment by rjbs** [comment]
Actually, it is, as of a day or two before you asked!  I'll update the documentation. :-)

**Comment by rjbs** [comment]
(Done in 9d5f6bd)
