### ISSUE TITLE
multipart/alternative not handled correctly if more than 2 parts

### ISSUE THREAD

**Issue by leejo** [rjbs/Email-Stuffer#33]
The code here: https://github.com/rjbs/Email-Stuffer/blob/master/lib/Email/Stuffer.pm#L584 # tries to handle the multipart/alternative Content-Type so we don't get, say, both text and html versions of an e-mail being displayed at the same time. However, if you have a text/plain part, text/html part, *and* an attachment (or several) this fails completely and you end up with the text and html being displayed at the same time in the e-mail client because the nesting of the parts w/r/t to the Content-Type isn't correct and there is no multipart/alternative instruction in the headers to allow the client to DTRT.

**Comment by simongreen-net** [comment]
This is a duplicate of issue #25 and should be fixed as part of the pull request I submitted for that issue.
