### ISSUE TITLE
Address issues from the v0.015 release

### ISSUE THREAD

**Issue by pali** [rjbs/Email-Stuffer#44]
* https://github.com/rjbs/Email-Stuffer/commit/0f3d7e6af83227578919400927fa14eceb69a045#commitcomment-22748005
* https://github.com/rjbs/Email-Stuffer/commit/8f8a2d51e5b724da59617d3356bc83bf2212698d#commitcomment-22747598
* https://github.com/rjbs/Email-Stuffer/commit/5f1c21eddaeba7ee2e230c5ebd4c5932e9e33371#commitcomment-22747842

**Comment by rjbs** [comment]
These have been addressed.
