### ISSUE TITLE
make transport an array option 

### ISSUE THREAD

**Issue by tomk3003** [rjbs/Email-Stuffer#45]
Hi there,

at the moment `transport` cannot be used like:

```
  Email::Stuffer->new({
    transport => [SMTP => host => 'my_smtp_server'],
  });

```
Enabling this in `%IS_ARRAY_ARG` seems to work out of the box.
Could you add that in a future version?

Thomas

**Comment by rjbs** [comment]
Sure thing, added in 7a8e9ba.
