### ISSUE TITLE
documentation typo: attribuet

### ISSUE THREAD

**Issue by KES777** [rjbs/Email-Stuffer#53]
https://metacpan.org/pod/Email::Stuffer#attach_file-$file-[,-$attribuet-=%3E-$value,-...-]

attach_file $file [, $attribuet => $value, ... ]

**Comment by bor** [comment]
It seems that this has already been fixed

#56 
#52

**Comment by rjbs** [comment]
Yup, I had quite a few people submit this fix!  Thanks, all. ;)
