### ISSUE TITLE
Is this documentation typo?

### ISSUE THREAD

**Issue by KES777** [rjbs/Email-Stuffer#59]
![image](https://user-images.githubusercontent.com/799021/96348595-aac21000-10b2-11eb-9415-ef5fda29a019.png)

**Comment by tomascohen** [comment]
It seems so.

**Comment by rjbs** [comment]
Fixed, thanks!

**Comment by KES777** [comment]
@rjbs Hi, thank you for fix. But it still inconsistent:
![image](https://user-images.githubusercontent.com/799021/211687047-58ea446c-5d04-43ba-9356-d71444f4dc1f.png)

I think it should be called as `$attribute => $value`, because at that position we put just one, then can repeat pair. And this fix should applied to all four sections: html_body, text_body, attach and attach_file.

**Comment by rjbs** [comment]
Thanks for this reply.  In my previous patch, I just sort of blindly did what I thought you asked.  I will, this time, carefully review the documentation myself and make sure I think I do something sensible.

**Comment by rjbs** [comment]
I believe this is better in v0.020, thank you.

**Comment by KES777** [comment]
Actually my first report was terrible.

Now your changes makes documentation really nice. There is no funny chars at the menu
![image](https://user-images.githubusercontent.com/799021/211751578-fcdc3e26-248e-497d-84d7-1f960fc22108.png)

and there is no bash syntax for optional arguments: `=method text_body $body [, $attributes => $value, ... ]`

But I have one more request:
```diff
-$stuffer->header($header_name = $value)
+$stuffer->header($header_name => $value)

**Comment by rjbs** [comment]
Thanks, I fixed that, but I don't plan to cut a new release just for that right now!
